### PR TITLE
Add Linux EGL as compilation option for StereoKitC

### PR DESCRIPTION
**Pull request by technobaboo**
This ensures EGL is an option to install for runtimes that support it, but leaves XLib as the default as it is more likely to function soon on the SteamVR OpenXR runtime.

@maluoi @slitcch could both of you review it when you have time, and could you add this to your cmake fork @slitcch?

### CODE REVIEW

**Comment by slitcch** [comment]
I couldn't get this to run on my system, got 
```
ERROR [client_gl_eglimage_swapchain_create] eglCreateImageKHR failed
XR_ERROR_RUNTIME_FAILURE in xrCreateSwapchain: Failed to create swapchain
[SK info] xrCreateSwapchain failed [XR_ERROR_RUNTIME_FAILURE]
[SK error] Couldn't create OpenXR view swapchains!
XR_ERROR_HANDLE_INVALID: xrDestroySwapchain(swapchain == NULL)
XR_ERROR_HANDLE_INVALID: xrDestroySwapchain(swapchain == NULL)
```
We need more testing by somebody other than me on Ubuntu/X11 to see why it's not working for me but works fine for you on Manjaro/Wayland.

**Comment by technobaboo** [comment]
for the record, I am not using Wayland. I have it installed on my system but it's not active. We narrowed down that it was mesa version specifically...

**Comment by maluoi** [comment]
I just tested this on my systems, EGL on Android still behaves fine, GLX on Linux still behaves fine as well, but EGL on Ubuntu seems to not work. Since EGL is exposed as a non-default compile flag, I'm gonna go ahead and merge this one in anyhow.

My Ubuntu machine is loading up EGL v1.5, and OpenGL ES 3.2 Mesa 20.2.6. From what I recall of the Discord discussion, it sounds like that's probably in the range of versions that wasn't really working for everyone else.

**Comment by maluoi** [comment]
I'll also try and backport changes to sk_gpu.h over to the [main repository](https://github.com/maluoi/sk_gpu) later today as well.

**Pull request merged**
